"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum
from .hand_bend import HandType

class ButtonState(Enum):
  """ボタンの状態"""
  RELEASED = ...
  TOUCHED = ...
  PRESSED = ...


@dataclass
class Joystick:
  """ジョイスティックの入力"""
  x: float
  y: float
  ...


@dataclass
class Trackpad:
  """トラックパッドの入力"""
  x: float
  y: float
  ...


@dataclass
class ControllerAnalog:
  """コントローラのアナログ入力"""
  trigger: float
  grip_value: float
  grip_force: float
  joystick: Joystick
  trackpad: Trackpad
  ...


@dataclass
class ControllerButtons:
  """コントローラのボタン入力"""
  a: ButtonState
  b: ButtonState
  sys: ButtonState
  trigger: ButtonState
  joystick: ButtonState
  trackpad: ButtonState
  ...


@dataclass
class ControllerInput:
  """コントローラの入力"""
  device_id: str
  hand_type: HandType
  buttons: ControllerButtons
  analog: ControllerAnalog
  ...


def parse_controller(args) -> ControllerInput:
  """コントローラの入力をパースする"""
  ...

