"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum

logger = ...
class DeviceType(Enum):
  """デバイス種別"""
  CONTACT_GLOVE = ...
  CONTACT_SHEET = ...
  CONTACT_GLOVE2 = ...


class DeviceColor(Enum):
  """デバイスカラー"""
  MAGENTA = ...
  RED = ...
  ORANGE = ...
  YELLOW = ...
  GREEN = ...
  CYAN = ...
  BLUE = ...
  GRAY = ...


@dataclass
class DeviceInfo:
  """デバイス情報"""
  id: str
  is_main: bool
  device_type: DeviceType
  name: str
  color: DeviceColor
  ping: float
  is_left_connected: bool
  left_battery: int
  left_ping: float
  is_right_connected: bool
  right_battery: int
  right_ping: float
  ...


def parse_device_info(args) -> list[DeviceInfo]:
  """デバイス情報をパースする"""
  ...

