"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from .hand_bend import HandType

@dataclass
class Wirst:
  """手首の回転量"""
  device_id: str
  hand_type: HandType
  w: float
  x: float
  y: float
  z: float
  ...


def parse_wrist(args) -> Wirst:
  """手首の回転量をパースする"""
  ...

